// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using practice_quiz.Models;

#nullable disable

namespace practice_quiz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702164759_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("practice_quiz.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizId"));

                    b.Property<int>("Answer")
                        .HasColumnType("integer")
                        .HasColumnName("answer_num");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Option1")
                        .HasColumnType("text")
                        .HasColumnName("option_1");

                    b.Property<string>("Option2")
                        .HasColumnType("text")
                        .HasColumnName("option_2");

                    b.Property<string>("Option3")
                        .HasColumnType("text")
                        .HasColumnName("option_3");

                    b.Property<string>("Option4")
                        .HasColumnType("text")
                        .HasColumnName("option_4");

                    b.HasKey("QuizId");

                    b.ToTable("quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
