// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using practice_quiz.Models;

#nullable disable

namespace practice_quiz.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250708073519_PlayerConId")]
    partial class PlayerConId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("practice_quiz.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_code");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("PlayerId");

                    b.HasIndex("RoomCode");

                    b.ToTable("player");
                });

            modelBuilder.Entity("practice_quiz.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("quiz_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuizId"));

                    b.Property<int>("Answer")
                        .HasColumnType("integer")
                        .HasColumnName("answer_num");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Option1")
                        .HasColumnType("text")
                        .HasColumnName("option_1");

                    b.Property<string>("Option2")
                        .HasColumnType("text")
                        .HasColumnName("option_2");

                    b.Property<string>("Option3")
                        .HasColumnType("text")
                        .HasColumnName("option_3");

                    b.Property<string>("Option4")
                        .HasColumnType("text")
                        .HasColumnName("option_4");

                    b.HasKey("QuizId");

                    b.ToTable("quiz");
                });

            modelBuilder.Entity("practice_quiz.Models.Room", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasColumnType("text")
                        .HasColumnName("room_code");

                    b.Property<bool>("GameStarted")
                        .HasColumnType("boolean")
                        .HasColumnName("game_started");

                    b.Property<string>("HostConnectionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host_connection_id");

                    b.HasKey("RoomCode");

                    b.ToTable("room");
                });

            modelBuilder.Entity("practice_quiz.Models.Player", b =>
                {
                    b.HasOne("practice_quiz.Models.Room", "Room")
                        .WithMany("Players")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("practice_quiz.Models.Room", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
